# Generated by Django 5.2.12 on 2026-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
